name: My first github action
on: [push]
jobs:
  print-hello-world:
    runs-on: ubuntu-latest
    steps:
      -uses: actions/checkout@v2
      -name: "print hello"
        run: echo "hello world!!!"
      -uses: actions/checkout@v2
      -name: "second job"
        run: echo "this second step"